### ISSUE TITLE
Former tribal getting hallucinations from powder

### ISSUE THREAD

**Issue by VEN0M5** [fortune13-ss13/Fortune13#498]

**Comment by Zembaflemba** [comment]
Tested it on a local server. Characters who spawn in as a tribal proper are given the increased healing rate and no hallucinations, however those with the Former Tribal perk get the same healing rate as everyone else. Not sure if intended, but I'll see about putting a PR up that changes it.

**Comment by VEN0M5** [comment]
My guess is the add trait is done incorrectly

https://github.com/fortune13-ss13/Fortune13/blob/master/code/datums/traits/good.dm

**Comment by Zembaflemba** [comment]
That's exactly what it is. The fix should be simple. I'll have a PR up once I'm done testing.

**Comment by Zembaflemba** [comment]
https://github.com/fortune13-ss13/Fortune13/pull/521

**Comment by Zembaflemba** [comment]
The fix was finally merged this can be closed.
