### ISSUE TITLE
Butcher knife missing model

### ISSUE THREAD

**Issue by KillerGryphon** [fortune13-ss13/Fortune13#555]
Simply put, when loading a server, including our server, you will get "MISSING ICON STATE knife_cleaver FOR /obj/item/kitchen/knife/butcher". The butcher knife is in the game still, but as the error says, we don't have the icon for it anymore. Someone please take a look at it and see how it got borked!

**Comment by Pebblesthe2nd** [comment]
Fix PR merged.
