### ISSUE TITLE
new oasis layout is not conducive to gameplay

### ISSUE THREAD

**Issue by cornercube** [fortune13-ss13/Fortune13#572]
overall consensus amongst oasis townsfolk is that the recent removal of the oasis under ground has negatively impacted it.
it is now much more cramped, has no more player housing, and lacks even basic amenities like showers and sinks to clean up
it also has several bugs, such as the shopkeep missing several key materials

it is in the best interests to revert that change until it can be re-implemented without totally gutting the town

**Comment by Wirpy** [comment]
https://github.com/fortune13-ss13/Fortune13/pull/579
